(define boder-painter
        (let ((point-a (make-vect 0 0))
              (point-b (make-vect 0 1))
              (point-c (make-vect 1 1))
              (point-d (make-vect 1 0)))
             (segments->painter (list (make-segment point-a point-b)
                                      (make-segment point-b point-c)
                                      (make-segment point-c point-d)
                                      (make-segment point-d point-a)))))

(define diagonal-painter
        (let ((point-a (make-vect 0 0))
              (point-b (make-vect 0 1))
              (point-c (make-vect 1 1))
              (point-d (make-vect 1 0)))
             (segments->painter (list (make-segment point-a point-c)
                                      (make-segment point-b point-d)))))

(define diamond-painter
        (let ((point-a (make-vect 0 0.5))
              (point-b (make-vect 0.5 1))
              (point-c (make-vect 1 0.5))
              (point-d (make-vect 0.5 0)))
             (segments->painter (list (make-segment point-a point-b)
                                      (make-segment point-b point-c)
                                      (make-segment point-c point-d)
                                      (make-segment point-d point-a)))))

(define wave
        (let ((point-a (make-vect 0 0.9))
              (point-b (make-vect 0.15 0.7))
              (point-c (make-vect 0.25 0.85))
              (point-d (make-vect 0.4 0.8))
              (point-e (make-vect 0.3 0.9))
              (point-f (make-vect 0.4 1))
              (point-g (make-vect 0.6 1))
              (point-h (make-vect 0.7 0.9))
              (point-i (make-vect 0.6 0.8))
              (point-j (make-vect 0.8 0.8))
              (point-k (make-vect 1 0.4))
              (point-l (make-vect 1 0.3))
              (point-m (make-vect 0.6 0.5))
              (point-n (make-vect 0.8 0))
              (point-o (make-vect 0.7 0))
              (point-p (make-vect 0.5 0.3))
              (point-q (make-vect 0.3 0))
              (point-r (make-vect 0.2 0))
              (point-s (make-vect 0.3 0.6))
              (point-t (make-vect 0.25 0.7))
              (point-u (make-vect 0.15 0.5))
              (point-v (make-vect 0 0.8)))
             (segments->painter (list (make-segment point-a point-b)
                                      (make-segment point-b point-c)
                                      (make-segment point-c point-d)
                                      (make-segment point-d point-e)
                                      (make-segment point-e point-f)
                                      (make-segment point-g point-h)
                                      (make-segment point-h point-i)
                                      (make-segment point-i point-j)
                                      (make-segment point-j point-k)
                                      (make-segment point-l point-m)
                                      (make-segment point-m point-n)
                                      (make-segment point-o point-p)
                                      (make-segment point-p point-q)
                                      (make-segment point-r point-s)
                                      (make-segment point-s point-t)
                                      (make-segment point-t point-u)
                                      (make-segment point-u point-v)))))