(define (get-num a b)
        (cond ((< a b) 0)
              ((= a b) 1)
              ((= b 0) 0)
              (else (+ (get-num (- a 1) (- b 1))
                       (get-num (- a 1) b)))))
;(display (get-num 6 4))

(define (iter-p m s)
        (display (get-num m s))
        (display "   ")
        (if (<  s  m)
          (iter-p m (+ 1 s))
          m))
;(iter-p 6 1)

(define (show row start)
        (iter-p start 1)
        (display "\n")
        (if (< start row)
            (show row (+ start 1))
            (display "..."))
)
(show 6 1)

(exit)