(load "LianXi_1.43.scm")
(define dx 0.000001)
(define (smooth f)
        (lambda (x)
                (/ (+ (f (- x dx))
                      (f x)
                      (f (+ x dx)))
                   3)))

(define (smooth-n f n)
        ((repeated smooth n) f))

(define (smooth-nn f n)
        (if (> n 1)
            (smooth-nn f (- n 1))
            (smooth f)))